config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :items, only: [:index, :show]
  delete "cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get "orders/thanks" => "orders#thanks"
  resources :orders, only: [:index, :new, :create, :show]
  post "orders/confirm" => "orders#confirm"
  resources :customers
  resources :addresses
  get "unsubscribe" => "customers#unsubscribe"
  post "deactivate" => "customers#deactivate"
  # 管理者側
  namespace :admin do

    get "homes" => "homes#top"
    get 'customers/:id/orders' => 'customers#show_order'
    resources :orders, only: [:show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :customers, only: [:index, :edit, :update, :show]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
layout 'admin'

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice:'変更が保存されました'
    else
      render:edit
    end
  end

  def show_order
    @customer = Customer.find(params[:id])
    @orders = @customer.orders
    @amount = 0
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def reject_user
    @customer = Customer.find_by(name: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_active == true)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_customer_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(current_customer), notice:'変更が保存されました'
    else
      render:edit
    end
  end

  def unsubscribe

  end
  def deactivate
    @customer = current_customer
    @customer.update(unsubscribe_params)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number,:is_active)
  end
  def unsubscribe_params
    params.permit(:is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class = 'container'>
  <div class = 'row'>
    <div class = 'col-3'>
      <h3 class = 'text-center'>会員情報編集</h3>
    </div>
  </div>
  <div class = 'row '>
    <div class = 'col-10'>
      <table class = 'table'>
        <%= form_with model:@customer, local:true do |f| %>
        <tbody>
          <tr>
            <td>氏名</td>
          <td>
            <%= f.label :（姓） %>
            <%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
          </td>

          <td>
              <%= f.label :（名） %>
              <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
            </div>
          </td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td>
            <%= f.label :（セイ） %>
            <%= f.text_field :last_name_kana, autofocus: true, class: 'form-control' %>
          </td>

          <td>
            <%= f.label :（メイ） %>
            <%= f.text_field :first_name_kana, autofocus: true, class: 'form-control' %>
          </td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td>
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td>
            <%= f.text_field :postal_code, autofocus: true, class: 'form-control' %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td colspan = '2'>
            <%= f.text_field :address, autofocus: true, class: 'form-control' %>
          </td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td>
              <%= f.text_field :telephone_number, autofocus: true, class: 'form-control' %>
          </td>
          <td></td>
        </tr>
        </tbody>


      </table>

      </div>
    </div>
    <div class = 'row justify-content-around'>
      <div class = 'col-4'>
        <%= f.submit '編集内容を保存', class: "btn btn-success" %>
      </div>

      <div class = 'col-3'>
        <%= link_to '退会する',unsubscribe_path, class: 'btn btn-danger text-right' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/customers/show.html.erb
<div class = 'container'>
  <div class = 'row'>
    <div class = 'col-3'>
      <h3 class = 'text-center mt-5'>マイページ</h3>
    </div>
  </div>
  <div class = 'row mt-5'>
    <div class = 'col-3'>
      <h3>登録情報</h3>
    </div>
    <div class = 'col-3'>
      <%= link_to '編集する', edit_customer_path(current_customer), class: 'btn btn-success' %>
    </div>
  </div>

    <div class = 'row mt-5'>
      <div class = 'col-12'>
        <table class = 'table'>
          <tbody>
            <tr>
              <th>氏名</th>
              <td><%= current_customer.last_name %><%= current_customer.first_name %></td>
              <td></td>
            </tr>
            <tr>
              <th>カナ</th>
              <td><%= current_customer.last_name_kana %><%= current_customer.first_name_kana %></td>
              <td></td>
            </tr>
            <tr>
              <th>郵便番号</th>
              <td><%= current_customer.postal_code %></td>
            </tr>
            <tr>
              <th>住所</th>
              <td><%= current_customer.address %></td>
              <td></td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= current_customer.telephone_number %></td>
              <td></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= current_customer.email %></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class = 'row'>
      <div class = 'col-3'>
        <h2>配送先</h2>
      </div>
      <div class = 'col-3'>
        <%= link_to '一覧を見る', addresses_path, class: 'btn btn-primary' %>
      </div>
    </div>

    <div class = 'row mt-2'>
      <div class = 'col-3'>
        <h2>注文履歴</h2>
      </div>
      <div class = 'col-3'>
        <%= link_to '一覧を見る', orders_path, class: 'btn btn-primary' %>
      </div>
    </div>

</div>

app/views/customers/unsubscribe.html.erb
<div class = 'container'>
  <div class = 'row justify-content-center mt-5'>
    <div class = 'col-5 text-center'>
      <h2>本当に退会しますか？</h2></br>
      <h3>退会すると、会員登録情報や</h3>
      <h3>これまでの購入履歴が閲覧できなくなります。</h3>
      <h3>退会する場合は、『退会する』をクリックしてください。</h3>
    </div>
  </div>
  <div class = 'row justify-content-center'>
    <div class = 'col-3 text-center'>
      <%= link_to '退会しない', customer_path(current_customer), class: 'btn btn-primary' %>
    </div>
    <div class = 'col-3 text-center'>
      <%= form_with url:deactivate_path, local:true do |f| %>
      <%= f.hidden_field :is_active, :value => false %>
      <%= f.submit '退会する', class: 'btn btn-danger', data: { confilm: "本当に退会しますか？" } %>
      <% end %>
    </div>
  </div>
</div>