config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :items, only: [:index, :show]
  delete "cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get "orders/thanks" => "orders#thanks"
  resources :orders, only: [:index, :new, :create, :show]
  post "orders/confirm" => "orders#confirm"
  resources :customers
  resources :addresses
  get "unsubscribe" => "customers#unsubscribe"
  post "deactivate" => "customers#deactivate"
  # 管理者側
  namespace :admin do

    get "homes" => "homes#top"
    get 'customers/:id/orders' => 'customers#show_order'
    resources :orders, only: [:show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :customers, only: [:index, :edit, :update, :show]
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  def index
    @cart_items = current_customer.cart_items
    @total_price = 0
  end

  def create
    cart_item = CartItem.new(cart_item_params)
    cart_item.customer_id = current_customer.id
    if cart_item.save
      redirect_to cart_items_path, notice:'カートに商品が追加されました'
    else
      redirect_to item_path(@item)
    end
  end

  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path, notice:'カート商品を全て削除しました'
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path, notice:'商品が１件削除されました'
  end



  private
  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<p class = 'text-success'><%= notice %></p>
<div class = 'container'>
  <div class = 'row mt-5'>
    <div class = 'col-3'>
      <h3 class = 'text-center'>ショッピングカート</h3>
    </div>
    <div class = 'col-9 text-right'>
      <%= link_to 'カートを空にする', cart_items_destroy_all_path, method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">商品名</th>
        <th scope="col">単価（税込み）</th>
        <th scope="col">数量</th>
        <th scope="col">小計</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |cart_item| %>
      <tr>
        <td>
          <%= link_to item_path(cart_item.item) do %>
            <%= attachment_image_tag cart_item.item, :image, :fill, 60, 40, fallback: "no_image.jpg" %>
            <%= cart_item.item.name %>
          <% end %>
        </td>
        <td><%= (cart_item.item.with_tax_price).round %></td>

        <td>
          <%= form_with model:cart_item, url:cart_item_path(cart_item), local:true do |f| %>
          <%= f.select :amount, [["１", "1"], ["２", "2"], ["３", "3"], ["４", "4"], ["５", "5"]], include_blank: "数量選択" %>
          <%= f.hidden_field :item_id, :value => cart_item.item.id %>
          <%= f.submit '変更', class: 'btn btn-success' %>
          <% end %>
        </td>

        <td><%= cart_item.subtotal %></td>
        <% @total_price += cart_item.subtotal %>
        <td><%= link_to '削除する', cart_item_path(cart_item), method: :delete, class: 'btn btn-danger' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class = 'row justify-content-between'>
    <div class = 'col-2'>
      <%= link_to '買い物を続ける', items_path, class: 'btn btn-primary' %>
    </div>
    <div class = 'col-5'>
      <table class = 'table'>
        <tr>
          <th class = 'table-secondary'>合計金額</th>
          <td><%= @total_price %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class = 'row justify-content-center'>
    <div class = 'col-4 '>
      <% if current_customer.cart_items.blank? %>
        <h2>商品がありません</h2>
      <% else %>
        <%= link_to "情報入力へ進む", new_order_path, class: 'btn btn-success btn-lg text-center' %>
      <% end %>
    </div>
  </div>
</div>