config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :items, only: [:index, :show]
  delete "cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get "orders/thanks" => "orders#thanks"
  resources :orders, only: [:index, :new, :create, :show]
  post "orders/confirm" => "orders#confirm"
  resources :customers
  resources :addresses
  get "unsubscribe" => "customers#unsubscribe"
  post "deactivate" => "customers#deactivate"
  # 管理者側
  namespace :admin do

    get "homes" => "homes#top"
    get 'customers/:id/orders' => 'customers#show_order'
    resources :orders, only: [:show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :customers, only: [:index, :edit, :update, :show]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def view_address_and_name
      self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  attachment :image
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { card: 0, bank: 1 }
  belongs_to :customer
  has_many :order_items

  def total_price
    billing_amount - postage
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  def subtotal
    self.purchase_price * self.amount
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = current_customer.addresses
    @address = Address.new
  end
  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path, notice:'配送先が追加されました'
    else
      @addresses = current_customer.addresses
      render :index
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render:edit
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:name, :address, :postal_code)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @genres = Genre.all
  end
  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
    @cart_item = CartItem.new
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    # @total = @order.order_items.inject(0) { |sum, purchase_price| sum + order_item.subtotal }
  end

  def new
    @order = Order.new
  end

  def confirm
    @postage = 800
    @total_price = 0
    @cart_items = current_customer.cart_items
    @select_address = params[:order][:select_address].to_i
    @order = Order.new(order_params)
    # @billing_amount = @total_price + @postage
    @order.billing_amount = @billing_amount
    @order.customer_id = current_customer.id

    if @select_address == 0
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code
      @order.name = current_customer.last_name + current_customer.first_name
    elsif @select_address == 1
      @address = Address.find(params[:order][:address_id])
      @order.address = @address.address
      @order.postal_code = @address.postal_code
      @order.name = @address.name
    end

  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    current_customer.cart_items.each do |cart_item|
      order_item = OrderItem.new
      order_item.item_id = cart_item.item_id
      order_item.order_id = @order.id
      order_item.amount = cart_item.amount
      order_item.purchase_price = cart_item.item.with_tax_price
      order_item.save
    end
    current_customer.cart_items.destroy_all

    redirect_to orders_thanks_path

  end



  private
  def order_params
    params.require(:order).permit(:payment_method, :address, :postal_code, :name, :billing_amount, :postage)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body calss = 'd-flex flex-column vh-100'>
    <header>
      <nav class = 'navbar navbar-expand-lg bg-light'>
        <div class = 'container'>
          <%= link_to "ながのCAKE(管理者)", admin_homes_path, class: 'navbar-brand p-3 text-dark' %>
          <div class = 'collapse navbar-collapse'>


            <div class = 'navbar-nav ml-auto'>

              <li class = 'nav-item'>
                <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark' %>
              </li>

              <li class = 'nav-item'>
                <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
              </li>

              <li class = 'nav-item'>
                <%= link_to '注文履歴一覧', admin_homes_path, class: 'nav-link text-dark' %>
              </li>

              <li class = 'nav-item'>
                <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %>
              </li>

              <li class = 'nav-item'>
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            </div>
          </div>

        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body calss = 'd-flex flex-column vh-100'>
    <header>
      <nav class = 'navbar navbar-expand-lg bg-light'>
        <div class = 'container'>
          <%= link_to "ながのCAKE", root_path, class: 'navbar-brand p-3 text-dark' %>
          <div class = 'collapse navbar-collapse'>


          <div class = 'navbar-nav ml-auto'>
            <% if customer_signed_in? %>

            <li class = 'nav-item'>
              <%= link_to 'マイページ', customer_path(current_customer), class: 'nav-link text-dark' %>
            </li>

            <li class = 'nav-item'>
              <%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %>
            </li>

            <li class = 'nav-item'>
              <%= link_to 'カート', cart_items_path, class: 'nav-link text-dark' %>
            </li>

            <li class = 'nav-item'>
              <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>

            <% else %>

            <li class = 'nav-item'>
              <%= link_to 'About', root_path, class: 'nav-link text-dark' %>
            </li>

            <li class = 'nav-item'>
              <%= link_to '商品一覧', root_path, class: 'nav-link text-dark' %>
            </li>

            <li class = 'nav-item'>
              <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>

            <li class = 'nav-item'>
              <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
          </div>
          </div>

        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>